apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-python-report
spec:
  params:
    - name: IMAGE
      type: string
      description: The image name to build
    - name: DOCKERFILE
      type: string
      description: Path to Dockerfile
    - name: CONTEXT
      type: string
      description: Build context
  steps:
    - name: build
      image: registry.access.redhat.com/ubi8/ubi-minimal
      command: ["/usr/bin/bash"]
      args: ["-c", "yum install -y buildah && buildah bud --tls-verify=false -t $(params.IMAGE) -f $(params.DOCKERFILE) $(params.CONTEXT) && buildah push $(params.IMAGE) --tls-verify=false"]
