{{- if .Values.backend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  labels:
    {{- include "thoughtsapp.labels" . | nindent 4 }}
    app: {{ .Values.backend.name }}
spec:
  ports:
  - name: http
    port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
  selector:
    app: {{ .Values.backend.name }}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  labels:
    {{- include "thoughtsapp.labels" . | nindent 4 }}
    app: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      containers:
      - name: {{ .Values.backend.name }}
        image: {{ .Values.backend.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.backend.port }}
          protocol: TCP
        env:
        - name: QUARKUS_DATASOURCE_JDBC_URL
          value: {{ include "thoughtsapp.postgresql.url" . }}
        - name: QUARKUS_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: database-user
        - name: QUARKUS_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: database-password
        - name: QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION
          value: {{ .Values.backend.hibernate.generation }}
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: {{ include "thoughtsapp.kafka.bootstrap" . }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
{{- if .Values.backend.route.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.backend.name }}
  labels:
    {{- include "thoughtsapp.labels" . | nindent 4 }}
    app: {{ .Values.backend.name }}
spec:
  {{- if or .Values.backend.route.host .Values.global.clusterDomain }}
  host: {{ .Values.backend.route.host | default (printf "%s-%s.%s" .Values.backend.name .Release.Namespace .Values.global.clusterDomain) }}
  {{- end }}
  to:
    kind: Service
    name: {{ .Values.backend.name }}
  port:
    targetPort: http
  {{- if .Values.backend.route.tls }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  {{- end }}
{{- end }}
{{- end }}
