{{- if .Values.evaluation.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secret
  labels:
    {{- include "thoughtsapp.labels" . | nindent 4 }}
    app: {{ .Values.evaluation.name }}
type: Opaque
stringData:
  OPENSHIFT_AI_ENDPOINT_URL: {{ .Values.evaluation.llm.endpoint | quote }}
  OPENSHIFT_AI_API_KEY: {{ .Values.evaluation.llm.apiKey | quote }}
  OPENAI_BASE_URL: {{ .Values.evaluation.llm.baseUrl | quote }}
  EMBEDDING_MODEL_NAME: {{ .Values.evaluation.llm.embeddingModel | quote }}
{{- end }}
