{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  labels:
    {{- include "thoughtsapp.labels" . | nindent 4 }}
    app: postgresql
type: Opaque
stringData:
  database-name: {{ .Values.postgresql.database | quote }}
  database-user: {{ .Values.postgresql.username | quote }}
  database-password: {{ .Values.postgresql.password | quote }}
{{- end }}
