---
apiVersion: v1
kind: Service
metadata:
  name: thoughts-frontend
  labels:
    app: thoughts-frontend
    app.kubernetes.io/part-of: thoughtsapp
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: thoughts-frontend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thoughts-frontend
  labels:
    app: thoughts-frontend
    app.kubernetes.io/part-of: thoughtsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thoughts-frontend
  template:
    metadata:
      labels:
        app: thoughts-frontend
    spec:
      containers:
      - name: thoughts-frontend
        image: quay.io/redhat_na_ssa/thoughtsapp-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: NEXT_PUBLIC_API_BASE_URL
          value: https://thoughts-backend-thoughts-app.apps.cluster-6pfqs.6pfqs.sandbox2325.opentlc.com
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: thoughts-frontend
  labels:
    app: thoughts-frontend
    app.kubernetes.io/part-of: thoughtsapp
spec:
  to:
    kind: Service
    name: thoughts-frontend
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
